// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlcgen

import (
	"context"
)

const health = `-- name: Health :one
SELECT 1::integer AS result
`

func (q *Queries) Health(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, health)
	var result int32
	err := row.Scan(&result)
	return result, err
}
